language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO="django>=1.5.0,<1.6.0"
  - DJANGO="django>=1.6.0,<1.7.0"
  - DJANGO="django>=1.7.0,<1.8.0"
  - DJANGO="django>=1.8.0,<1.9.0"
  - DJANGO="django>=1.9.0,<1.10.0"
matrix:
  exclude:
  - python: "2.6"
    env: DJANGO="django>=1.7.0,<1.8.0"
  - python: "2.6"
    env: DJANGO="django>=1.8.0,<1.9.0"
  - python: "2.6"
    env: DJANGO="django>=1.9.0,<1.10.0"
  - python: "3.3"
    env: DJANGO="django>=1.4.0,<1.5.0"

install:
  - travis_retry pip install -q coveralls  # installs coverage
  - travis_retry pip install $DJANGO
  - pip install -e .

script:
  - coverage run --source=example/article,parler runtests.py

after_success:
  - coveralls --verbose

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - travis@edoburu.nl
    on_success: never
    on_failure: always
