name: CI Testing
on:
  pull_request:
    branches:
      - master
  push:
    branches: [master, multiDB_support]
  workflow_dispatch:

jobs:
  test:
    name: "Python ${{ matrix.python }} Django ${{ matrix.django }}"
    runs-on: ubuntu-latest
    strategy:
      # max-parallel: 8  # default is max available
      fail-fast: false
      matrix:
        include:
          # Django 2.2
          - django: "2.2"
            python: "3.6"
          - django: "2.2"
            python: "3.7"
          - django: "2.2"
            python: "3.8"
          - django: "2.2"
            python: "3.9"
          # Django 3.1
          - django: "3.1"
            python: "3.6"
          - django: "3.1"
            python: "3.7"
          - django: "3.1"
            python: "3.8"
          - django: "3.1"
            python: "3.9"
          # Django 3.2
          - django: "3.2"
            python: "3.6"
          - django: "3.2"
            python: "3.7"
          - django: "3.2"
            python: "3.8"
          - django: "3.2"
            python: "3.9"
          - django: "3.2"
            python: "3.10"
          # Django 4.0
          - django: "4.0"
            python: "3.9"
          - django: "4.0"
            python: "3.10"
          # Django 4.1
          - django: "4.1"
            python: "3.9"
          - django: "4.1"
            python: "3.10"
          # Django 4.2
          - django: "4.2"
            python: "3.9"
          - django: "4.2"
            python: "3.10"

    steps:
      - name: Install gettext
        run: sudo apt-get install -y gettext

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Packages
        run: |
          python -m pip install -U pip
          python -m pip install "Django~=${{ matrix.django }}" codecov -e .[tests]

      - name: Run Tests
        run: |
          echo "Python ${{ matrix.python }} / Django ${{ matrix.django }}"
          coverage run --rcfile=.coveragerc runtests.py
          codecov
        continue-on-error: ${{ contains(matrix.django, '4.0') }}
